#!/bin/bash

# Verify options and abort if there is a error
#$ -w e

# Choose parallel environment
#$ -pe mpi 32

# Specify the job name in the queue system
#$ -N dask-example

# Start the script in the current working directory
#$ -cwd

# Time requirements
#$ -l h_rt=120:00:00
#$ -l s_rt=120:00:00

# Activate your environment here!
module load python/3.9
source ./mpi-test/bin/activate

# Run script
mpirun -np 32 python3 dask-example.py -s shot_files/M9.csv -n ip -e 10000